kind: ConfigMap
apiVersion: v1
metadata:
  name: panel-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: panel
data:
  application.yaml: |
    spring:
      application.name: panel-gateway
    server:
      port: 8080

---

kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: panel-gateway
  namespace: {{ .Release.Namespace }}
spec:
  lookupPolicy:
    local: false

---

apiVersion: v1
kind: Service
metadata:
  name: panel-gateway
spec:
  selector:
    app: panel-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-uri: 'https://github.com/GC-Genome/panel-project-2nd/tree/master/gateway'
    configmap.reloader.stakater.com/reload: "panel-gateway"
  name: panel-gateway
  namespace: {{ .Release.Namespace }}
  finalizers:
    - foregroundDeletion
  labels:
    app: panel-gateway
    app.kubernetes.io/component: panel
    app.kubernetes.io/instance: panel
    app.kubernetes.io/name: panel
    app.kubernetes.io/part-of: panel
    app.openshift.io/runtime: spring-boot
    app.openshift.io/runtime-namespace: {{ .Release.Namespace }}
    app.openshift.io/runtime-version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel-gateway
  template:
    metadata:
      labels:
        app: panel-gateway
        version: 0.0.1
        deployment: panel-gateway
    spec:
      volumes:
        - name: config
          configMap:
            name: panel-gateway
            defaultMode: 420
      containers:
        - name: panel-gateway
        {{- if index .Values "panel-gateway" }}
          image: {{ index .Values "panel-gateway" "image" "name" }}:{{ index .Values "panel-gateway" "image" "tag" }}
        {{- else }}
          image: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/panel-gateway:latest
        {{- end }}
          ports:
            - containerPort: 8080
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Seoul
          volumeMounts:
            - name: config
              mountPath: /app/resources/application.yaml
              subPath: application.yaml
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 0
  progressDeadlineSeconds: 600
  paused: false
