spring:
  application:
    name: bi-service
  main:
    web-application-type: reactive
  cloud:
    zookeeper:
      connect-string: test:12181
      discovery:
        root: /panel-services
  r2dbc:
    url: r2dbc:postgresql://pisces:5432/lims
    username: panel
    password: snubi1004
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
server:
  port: 62419